export const GET_ERRORS = 'GET_ERRORS'
export const SERVER_RESPONSE = 'SERVER_RESPONSE'

export const SET_FAKE_CURRENT_USER = 'SET_FAKE_CURRENT_USER'
export const LIST_FAKE_USERS = 'LIST_FAKE_USERS'
export const FAKE_USERS_LOADING = 'FAKE_USERS_LOADING'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LIST_USERS = 'LIST_USERS'

export const USER_LOADING = 'USER_LOADING'
